version: 0.2
env:
  variables:
    S3_BUCKET: "calsoft-one-web-test"
phases:
  install:
    runtime-versions:
      nodejs: 14
    pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd Calsoft-one/client/waffle
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - cd dist
      - aws s3 sync . s3://${S3_BUCKET}
      - echo Build completed on `date`

artifacts:
  files: '**/*'
  discard-paths: yes
